# Generated by Django 5.1.7 on 2025-04-03 15:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('booked', 'Booked'), ('arrived', 'Arrived'), ('left', 'Left'), ('rejected', 'Rejected')], default='booked', max_length=100),
        ),
        migrations.AlterField(
            model_name='floor',
            name='parking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='floors', to='app.parking'),
        ),
    ]
