# Generated by Django 5.1.7 on 2025-04-03 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_booking_status_alter_floor_parking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='arrived_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='left_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='rejected_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
